version: '3.8'
services:
  frontend:
    container_name: frontend_container
    build:
      context: .
      target: frontend
    ports:
      - "80:8080"
    depends_on:
      - backend

  backend:
    container_name: backend_container
    build:
      context: .
      target: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
